-- Generated by Oracle SQL Developer Data Modeler 24.3.0.240.1210
--   at:        2024-12-16 11:54:46 MSK
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE address (
    address_id             INTEGER NOT NULL,
    house_id_house         INTEGER,
    apartment_apartment_id INTEGER,
    client_client_id       INTEGER NOT NULL
);

ALTER TABLE address
    ADD CONSTRAINT arc_1
        CHECK ( ( ( house_id_house IS NOT NULL )
                  AND ( apartment_apartment_id IS NULL ) )
                OR ( ( apartment_apartment_id IS NOT NULL )
                     AND ( house_id_house IS NULL ) )
                OR ( ( house_id_house IS NULL )
                     AND ( apartment_apartment_id IS NULL ) ) );

CREATE UNIQUE INDEX address__idx ON
    address (
        house_id_house
    ASC );

CREATE UNIQUE INDEX address__idxv1 ON
    address (
        apartment_apartment_id
    ASC );

ALTER TABLE address ADD CONSTRAINT address_pk PRIMARY KEY ( address_id );

CREATE TABLE apartment (
    apartment_id   INTEGER NOT NULL,
    apartment_num  INTEGER NOT NULL,
    house_id_house INTEGER NOT NULL
);

ALTER TABLE apartment ADD CONSTRAINT apartment_pk PRIMARY KEY ( apartment_id );

CREATE TABLE banquet_hall (
    id                       INTEGER NOT NULL,
    restaurant_restaurant_id INTEGER NOT NULL,
    capacity                 INTEGER NOT NULL
);

ALTER TABLE banquet_hall ADD CONSTRAINT banquet_hall_pk PRIMARY KEY ( id );

CREATE TABLE booking (
    booking_id       INTEGER NOT NULL,
    booking_date     DATE NOT NULL,
    num_guests       INTEGER NOT NULL,
    client_client_id INTEGER NOT NULL,
    table_table_id   INTEGER NOT NULL,
    banquet_hall_id  INTEGER NOT NULL
);

ALTER TABLE booking ADD CONSTRAINT booking_pk PRIMARY KEY ( booking_id );

CREATE TABLE cart (
    cart_id          INTEGER NOT NULL,
    orders_order_id  INTEGER NOT NULL,
    menu_position_id INTEGER NOT NULL,
    quantity         INTEGER NOT NULL,
    price            INTEGER NOT NULL
);

ALTER TABLE cart ADD CONSTRAINT cart_pk PRIMARY KEY ( cart_id );

CREATE TABLE category (
    category_id   INTEGER NOT NULL,
    category_name VARCHAR2(30) NOT NULL
);

ALTER TABLE category ADD CONSTRAINT category_pk PRIMARY KEY ( category_id );

CREATE TABLE city (
    city_id            INTEGER NOT NULL,
    city_name          VARCHAR2(30) NOT NULL,
    country_country_id INTEGER NOT NULL
);

ALTER TABLE city ADD CONSTRAINT city_pk PRIMARY KEY ( city_id );

CREATE TABLE client (
    client_id          INTEGER NOT NULL,
    client_name        VARCHAR2(30) NOT NULL,
    client_surname     VARCHAR2(30) NOT NULL,
    client_email       VARCHAR2(255),
    telephone_phone_id INTEGER NOT NULL
);

CREATE UNIQUE INDEX client__idx ON
    client (
        telephone_phone_id
    ASC );

ALTER TABLE client ADD CONSTRAINT client_pk PRIMARY KEY ( client_id );

CREATE TABLE country (
    country_id   INTEGER NOT NULL,
    country_name VARCHAR2(30) NOT NULL
);

ALTER TABLE country ADD CONSTRAINT country_pk PRIMARY KEY ( country_id );

CREATE TABLE diploma (
    diploma_id           INTEGER NOT NULL,
    diploma_series       VARCHAR2(50) NOT NULL,
    diploma_num          VARCHAR2(50) NOT NULL,
    employee_employee_id INTEGER NOT NULL,
    diploma_id1          NUMBER NOT NULL
);

ALTER TABLE diploma ADD CONSTRAINT diploma_pk PRIMARY KEY ( diploma_id1 );

CREATE TABLE education_level (
    id                  INTEGER NOT NULL,
    education_level     VARCHAR2(50) NOT NULL,
    diploma_diploma_id1 NUMBER NOT NULL
);

ALTER TABLE education_level ADD CONSTRAINT education_level_pk PRIMARY KEY ( id );

CREATE TABLE educational_institution (
    id                  INTEGER NOT NULL,
    name                VARCHAR2(30) NOT NULL,
    diploma_diploma_id1 NUMBER NOT NULL
);

ALTER TABLE educational_institution ADD CONSTRAINT educational_institution_pk PRIMARY KEY ( id );

CREATE TABLE employee (
    employee_id              INTEGER NOT NULL,
    name                     VARCHAR2(30) NOT NULL,
    last_name                VARCHAR2(30) NOT NULL,
    surname                  VARCHAR2(30),
    gender                   VARCHAR2(1) NOT NULL,
    role                     VARCHAR2(30) NOT NULL,
    telephone_phone_id       INTEGER NOT NULL,
    restaurant_restaurant_id INTEGER NOT NULL
);

CREATE UNIQUE INDEX employee__idx ON
    employee (
        telephone_phone_id
    ASC );

ALTER TABLE employee ADD CONSTRAINT employee_pk PRIMARY KEY ( employee_id );

CREATE TABLE event (
    event_id        INTEGER NOT NULL,
    event_name      VARCHAR2(30) NOT NULL,
    description     VARCHAR2(255) NOT NULL,
    date_start      DATE NOT NULL,
    date_end        DATE NOT NULL,
    banquet_hall_id INTEGER NOT NULL
);

ALTER TABLE event ADD CONSTRAINT event_pk PRIMARY KEY ( event_id );

CREATE TABLE house (
    id_house         INTEGER NOT NULL,
    house_num        INTEGER NOT NULL,
    street_id_street INTEGER NOT NULL
);

ALTER TABLE house ADD CONSTRAINT house_pk PRIMARY KEY ( id_house );

CREATE TABLE ingredient (
    ingredient_id INTEGER NOT NULL,
    name          VARCHAR2(30) NOT NULL,
    unit          VARCHAR2(30) NOT NULL
);

ALTER TABLE ingredient ADD CONSTRAINT ingredient_pk PRIMARY KEY ( ingredient_id );

CREATE TABLE instructions (
    instruction_id INTEGER NOT NULL,
    instructions   VARCHAR2(255) NOT NULL
);

ALTER TABLE instructions ADD CONSTRAINT instructions_pk PRIMARY KEY ( instruction_id );

CREATE TABLE menu (
    position_id          INTEGER NOT NULL,
    position_name        VARCHAR2(30) NOT NULL,
    position_description VARCHAR2(255) NOT NULL,
    position_price       INTEGER NOT NULL,
    category_category_id INTEGER NOT NULL
);

ALTER TABLE menu ADD CONSTRAINT menu_pk PRIMARY KEY ( position_id );

CREATE TABLE order_status (
    order_status_id   INTEGER NOT NULL,
    order_status_name VARCHAR2(30) NOT NULL
);

ALTER TABLE order_status ADD CONSTRAINT order_status_pk PRIMARY KEY ( order_status_id );

CREATE TABLE orders (
    order_id                     INTEGER NOT NULL,
    order_date                   DATE NOT NULL,
    required_date                DATE NOT NULL,
    order_total_amount           INTEGER NOT NULL,
    address_address_id           INTEGER NOT NULL,
    order_status_order_status_id INTEGER NOT NULL,
    client_client_id             INTEGER NOT NULL,
    payment_payment_id           INTEGER NOT NULL
);

CREATE UNIQUE INDEX orders__idx ON
    orders (
        payment_payment_id
    ASC );

ALTER TABLE orders ADD CONSTRAINT orders_pk PRIMARY KEY ( order_id );

CREATE TABLE payment (
    payment_id     INTEGER NOT NULL,
    "date"         DATE NOT NULL,
    payment_method VARCHAR2(30) NOT NULL,
    amount         NUMBER(9, 2) NOT NULL
);

ALTER TABLE payment ADD CONSTRAINT payment_pk PRIMARY KEY ( payment_id );

CREATE TABLE purchasing_ingredients (
    purchase_id              INTEGER NOT NULL,
    ingredient_ingredient_id INTEGER NOT NULL,
    supplier_supplier_id     INTEGER NOT NULL,
    quantity                 INTEGER NOT NULL,
    price                    NUMBER(9, 2) NOT NULL,
    "date"                   DATE NOT NULL
);

ALTER TABLE purchasing_ingredients ADD CONSTRAINT purchasing_ingredients_pk PRIMARY KEY ( purchase_id );

CREATE TABLE qualification (
    qualification_id    INTEGER NOT NULL,
    qualification_name  VARCHAR2(50) NOT NULL,
    diploma_diploma_id1 NUMBER NOT NULL
);

ALTER TABLE qualification ADD CONSTRAINT qualification_pk PRIMARY KEY ( qualification_id );

CREATE TABLE recipe (
    recipe_id                   INTEGER NOT NULL,
    menu_position_id            INTEGER NOT NULL,
    ingredient_ingredient_id    INTEGER NOT NULL,
    instructions_instruction_id INTEGER NOT NULL,
    quantity                    NUMBER(9, 2) NOT NULL
);

CREATE UNIQUE INDEX recipe__idx ON
    recipe (
        menu_position_id
    ASC );

CREATE UNIQUE INDEX recipe__idxv1 ON
    recipe (
        instructions_instruction_id
    ASC );

ALTER TABLE recipe ADD CONSTRAINT recipe_pk PRIMARY KEY ( recipe_id );

CREATE TABLE restaurant (
    restaurant_id      INTEGER NOT NULL,
    restaurant_name    VARCHAR2(30) NOT NULL,
    house_id_house     INTEGER NOT NULL,
    telephone_phone_id INTEGER NOT NULL
);

CREATE UNIQUE INDEX restaurant__idx ON
    restaurant (
        house_id_house
    ASC );

CREATE UNIQUE INDEX restaurant__idxv1 ON
    restaurant (
        telephone_phone_id
    ASC );

ALTER TABLE restaurant ADD CONSTRAINT restaurant_pk PRIMARY KEY ( restaurant_id );

CREATE TABLE schedule (
    schedule_id          INTEGER NOT NULL,
    shift_start          DATE NOT NULL,
    shift_end            DATE NOT NULL,
    week_day             VARCHAR2(30) NOT NULL,
    employee_employee_id INTEGER NOT NULL
);

ALTER TABLE schedule ADD CONSTRAINT schedule_pk PRIMARY KEY ( schedule_id );

CREATE TABLE speciality (
    speciality_id       INTEGER NOT NULL,
    speciality_name     VARCHAR2(50) NOT NULL,
    speciality_code     VARCHAR2(30),
    diploma_diploma_id1 NUMBER NOT NULL
);

ALTER TABLE speciality ADD CONSTRAINT speciality_pk PRIMARY KEY ( speciality_id );

CREATE TABLE street (
    id_street    INTEGER NOT NULL,
    street_name  VARCHAR2(30) NOT NULL,
    city_city_id INTEGER NOT NULL
);

ALTER TABLE street ADD CONSTRAINT street_pk PRIMARY KEY ( id_street );

CREATE TABLE supplier (
    supplier_id   INTEGER NOT NULL,
    supplier_name VARCHAR2(30) NOT NULL
);

ALTER TABLE supplier ADD CONSTRAINT supplier_pk PRIMARY KEY ( supplier_id );

CREATE TABLE tables (
    table_id                 INTEGER NOT NULL,
    restaurant_restaurant_id INTEGER NOT NULL,
    table_num                INTEGER NOT NULL,
    capacity                 INTEGER NOT NULL
);

ALTER TABLE tables ADD CONSTRAINT table_pk PRIMARY KEY ( table_id );

CREATE TABLE telephone (
    phone_id  INTEGER NOT NULL,
    phone_num VARCHAR2(30) NOT NULL
);

ALTER TABLE telephone ADD CONSTRAINT telephone_pk PRIMARY KEY ( phone_id );

CREATE TABLE warehouse (
    id                       INTEGER NOT NULL,
    ingredient_ingredient_id INTEGER NOT NULL,
    quantity                 NUMBER(9, 2) NOT NULL
);

CREATE UNIQUE INDEX warehouse__idx ON
    warehouse (
        ingredient_ingredient_id
    ASC );

ALTER TABLE warehouse ADD CONSTRAINT warehouse_pk PRIMARY KEY ( id );

ALTER TABLE address
    ADD CONSTRAINT address_apartment_fk FOREIGN KEY ( apartment_apartment_id )
        REFERENCES apartment ( apartment_id );

ALTER TABLE address
    ADD CONSTRAINT address_client_fk
        FOREIGN KEY ( client_client_id )
            REFERENCES client ( client_id )
                ON DELETE CASCADE;

ALTER TABLE address
    ADD CONSTRAINT address_house_fk FOREIGN KEY ( house_id_house )
        REFERENCES house ( id_house );

ALTER TABLE apartment
    ADD CONSTRAINT apartment_house_fk FOREIGN KEY ( house_id_house )
        REFERENCES house ( id_house );

ALTER TABLE banquet_hall
    ADD CONSTRAINT banquet_hall_restaurant_fk FOREIGN KEY ( restaurant_restaurant_id )
        REFERENCES restaurant ( restaurant_id );

ALTER TABLE booking
    ADD CONSTRAINT booking_banquet_hall_fk FOREIGN KEY ( banquet_hall_id )
        REFERENCES banquet_hall ( id );

ALTER TABLE booking
    ADD CONSTRAINT booking_client_fk FOREIGN KEY ( client_client_id )
        REFERENCES client ( client_id );

ALTER TABLE booking
    ADD CONSTRAINT booking_table_fk FOREIGN KEY ( table_table_id )
        REFERENCES tables ( table_id );

ALTER TABLE cart
    ADD CONSTRAINT cart_menu_fk
        FOREIGN KEY ( menu_position_id )
            REFERENCES menu ( position_id )
                ON DELETE CASCADE;

ALTER TABLE cart
    ADD CONSTRAINT cart_orders_fk
        FOREIGN KEY ( orders_order_id )
            REFERENCES orders ( order_id )
                ON DELETE CASCADE;

ALTER TABLE city
    ADD CONSTRAINT city_country_fk FOREIGN KEY ( country_country_id )
        REFERENCES country ( country_id );

ALTER TABLE client
    ADD CONSTRAINT client_telephone_fk FOREIGN KEY ( telephone_phone_id )
        REFERENCES telephone ( phone_id );

ALTER TABLE diploma
    ADD CONSTRAINT diploma_employee_fk FOREIGN KEY ( employee_employee_id )
        REFERENCES employee ( employee_id );

ALTER TABLE education_level
    ADD CONSTRAINT education_level_diploma_fk FOREIGN KEY ( diploma_diploma_id1 )
        REFERENCES diploma ( diploma_id1 );

--  ERROR: FK name length exceeds maximum allowed length(30) 
ALTER TABLE educational_institution
    ADD CONSTRAINT educational_institution_diploma_fk FOREIGN KEY ( diploma_diploma_id1 )
        REFERENCES diploma ( diploma_id1 );

ALTER TABLE employee
    ADD CONSTRAINT employee_restaurant_fk FOREIGN KEY ( restaurant_restaurant_id )
        REFERENCES restaurant ( restaurant_id );

ALTER TABLE employee
    ADD CONSTRAINT employee_telephone_fk FOREIGN KEY ( telephone_phone_id )
        REFERENCES telephone ( phone_id );

ALTER TABLE event
    ADD CONSTRAINT event_banquet_hall_fk FOREIGN KEY ( banquet_hall_id )
        REFERENCES banquet_hall ( id );

ALTER TABLE house
    ADD CONSTRAINT house_street_fk FOREIGN KEY ( street_id_street )
        REFERENCES street ( id_street );

ALTER TABLE menu
    ADD CONSTRAINT menu_category_fk FOREIGN KEY ( category_category_id )
        REFERENCES category ( category_id );

ALTER TABLE orders
    ADD CONSTRAINT orders_address_fk FOREIGN KEY ( address_address_id )
        REFERENCES address ( address_id );

ALTER TABLE orders
    ADD CONSTRAINT orders_client_fk FOREIGN KEY ( client_client_id )
        REFERENCES client ( client_id );

ALTER TABLE orders
    ADD CONSTRAINT orders_order_status_fk
        FOREIGN KEY ( order_status_order_status_id )
            REFERENCES order_status ( order_status_id )
                ON DELETE CASCADE;

ALTER TABLE orders
    ADD CONSTRAINT orders_payment_fk FOREIGN KEY ( payment_payment_id )
        REFERENCES payment ( payment_id );

--  ERROR: FK name length exceeds maximum allowed length(30) 
ALTER TABLE purchasing_ingredients
    ADD CONSTRAINT purchasing_ingredients_ingredient_fk FOREIGN KEY ( ingredient_ingredient_id )
        REFERENCES ingredient ( ingredient_id );

--  ERROR: FK name length exceeds maximum allowed length(30) 
ALTER TABLE purchasing_ingredients
    ADD CONSTRAINT purchasing_ingredients_supplier_fk FOREIGN KEY ( supplier_supplier_id )
        REFERENCES supplier ( supplier_id );

ALTER TABLE qualification
    ADD CONSTRAINT qualification_diploma_fk FOREIGN KEY ( diploma_diploma_id1 )
        REFERENCES diploma ( diploma_id1 );

ALTER TABLE recipe
    ADD CONSTRAINT recipe_ingredient_fk FOREIGN KEY ( ingredient_ingredient_id )
        REFERENCES ingredient ( ingredient_id );

ALTER TABLE recipe
    ADD CONSTRAINT recipe_instructions_fk FOREIGN KEY ( instructions_instruction_id )
        REFERENCES instructions ( instruction_id );

ALTER TABLE recipe
    ADD CONSTRAINT recipe_menu_fk
        FOREIGN KEY ( menu_position_id )
            REFERENCES menu ( position_id )
                ON DELETE CASCADE;

ALTER TABLE restaurant
    ADD CONSTRAINT restaurant_house_fk FOREIGN KEY ( house_id_house )
        REFERENCES house ( id_house );

ALTER TABLE restaurant
    ADD CONSTRAINT restaurant_telephone_fk FOREIGN KEY ( telephone_phone_id )
        REFERENCES telephone ( phone_id );

ALTER TABLE schedule
    ADD CONSTRAINT schedule_employee_fk FOREIGN KEY ( employee_employee_id )
        REFERENCES employee ( employee_id );

ALTER TABLE speciality
    ADD CONSTRAINT speciality_diploma_fk FOREIGN KEY ( diploma_diploma_id1 )
        REFERENCES diploma ( diploma_id1 );

ALTER TABLE street
    ADD CONSTRAINT street_city_fk FOREIGN KEY ( city_city_id )
        REFERENCES city ( city_id );

ALTER TABLE tables
    ADD CONSTRAINT table_restaurant_fk FOREIGN KEY ( restaurant_restaurant_id )
        REFERENCES restaurant ( restaurant_id );

ALTER TABLE warehouse
    ADD CONSTRAINT warehouse_ingredient_fk FOREIGN KEY ( ingredient_ingredient_id )
        REFERENCES ingredient ( ingredient_id );

CREATE SEQUENCE diploma_diploma_id1_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER diploma_diploma_id1_trg BEFORE
    INSERT ON diploma
    FOR EACH ROW
    WHEN ( new.diploma_id1 IS NULL )
BEGIN
    :new.diploma_id1 := diploma_diploma_id1_seq.nextval;
END;
/



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            32
-- CREATE INDEX                            10
-- ALTER TABLE                             70
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           1
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          1
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   3
-- WARNINGS                                 0
